# Generated by Django 5.1.6 on 2025-03-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_remove_person_birth_date_alter_person_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
